apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cs-unoconvsvc
  labels:
    k8s-app: {{ .Release.Name }}-cs-unoconvsvc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    k8s-app: {{ .Release.Name }}-cs-unoconvsvc
